### ISSUE TITLE
USER ERROR: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value

### ISSUE THREAD

**Issue by mys** [steemnova/steemnova#102]
USER ERROR: "SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x98\x82' for column 'message_text' at row 1

Query-Code:INSERT INTO uni1_messages SET
                message_owner           = 38,
                message_sender          = 19,
                message_time            = 1522445518,
                message_type            = 1,
                message_from            = mys [1:17:8],
                message_subject         = TEST2,
                message_text            = 😂,
                message_unread          = 1,
                message_universe        = 1;

Error while sending message with emoticon.

**Comment by cryptoriddlerUIO** [comment]
It's a problem with the utf8 encoding in MySQL which uses only 3 bytes for encoding, but 4 bytes are needed for real UTF-8 encoding.
As you can see in the error message, the emoji is encoded as '\xF0\x9F\x98\x82'. So it needs 4 bytes to store the character, but MySQLs utf8 encoding supports only 3 bytes.

Changing the character set from utf8 to utf8mb4 should solve issue.

**Comment by hussnainsheikh** [comment]
This issue should be closed now. :)

**Comment by saadzizi** [comment]
Hello ! so I have the same problem with this entry    "   【𝐏𝐫𝐢𝐧𝐭𝐞𝐦𝐩𝐬 𝐕𝐞𝐧𝐭𝐞 𝐂𝐚𝐝𝐞𝐚𝐮】 " 
`SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xF0\\x9D\\x90\\x8F\\xF0\\x9D...'`
