### ISSUE TITLE
Critical vulnerability XSS (Cross Site Scripting) Steemnova (fixed)

### ISSUE THREAD

**Issue by louis88-steemit** [steemnova/steemnova#105]
#### Expected behavior
When I play the browser game SteemNova, I expect that I can play a game that is free of dangerous security vulnerabilities. In particular, I expect that there is no vulnerability that can endanger other players in the game or introduce malware on a computer. 

#### Actual behavior
Unfortunately I discovered a security hole that can not only affect the game but can also be dangerous for other players of the game. The vulnerability found is an XSS (Cross-Site Scripting) vulnerability and can be set in the area of an alliance administration. Since there is an editor (TinyMCE) here that allows this vulnerability to be infiltrated. 

A big thank you goes to the developer team and the project owner who took care of this vulnerability at short notice and have already implemented it in the live system. This went so far without big problems about which I am very happy.

#### How to reproduce
The problem has now been resolved. It was previously possible to reload malware with Javascript if you used this command among others. (demonstration)

    [url=javascript:alert(String.fromCharCode(88,83,83))]http://google.com/[/url]

* Browser:  Chrome Version 65.0.3325.146 (Offizieller Build) (64-Bit)
* Operating system: Mac os x

#### Recording Of The Bug

Demonstration.
![enter image description here](https://i.imgur.com/JyAQbOa.gif)
    

Thanks to the project leaders and developers who solved the problem very quickly! 
@louis88

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@louis88/critical-vulnerability-xss-cross-site-scripting-steemnova-fixed">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/103
