### ISSUE TITLE
Wrong implementation of the bashing rule

### ISSUE THREAD

**Issue by a-dalora** [steemnova/steemnova#108]
#### Expected behavior
Attacking an active player more than six times a day is prevented by the software applying the bashing rule. This rule does not protect inactive players in any way.

#### Actual behavior
On the page https://steemnova.intinte.org/ attacking an inactive player more than six times in one day is prevented by the software automatically. It is not possible to farm the planet further.
#### How to reproduce
Attack an allready inactive player at the same planet seven times in one day.

* Browser: all browsers
* Operating system: all operating systems

#### Recording Of The Bug
<center>
![galaxieview_140.png](https://cdn.utopian.io/posts/7224cbb57b9b28e698733e3e4a28c5534c6cgalaxieview_140.png)
![attack_14.png](https://cdn.utopian.io/posts/825364443570b98c9d3ae929820d7ac99d9dattack_14.png)
![bash-notice.png](https://cdn.utopian.io/posts/fa999cc5e9ffa3d10a36f01c6f649091f508bash-notice.png)

</center>
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@a-dalora/wrong-implementation-of-the-bashing-rule">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/109
