### ISSUE TITLE
 logo for steem nova

### ISSUE THREAD

**Issue by damahboy** [steemnova/steemnova#118]
HI STEEM NOVA ,,
introduce me @damahsyari
I am a graphic designer, I have finished designing for you today: D
hopefully you can be happy with my design, 

![11](https://user-images.githubusercontent.com/38080324/38654591-4e4f32e6-3e3a-11e8-869b-0bcbb6817d26.png)

Logo Varian

![2](https://user-images.githubusercontent.com/38080324/38654595-56990e22-3e3a-11e8-945d-e20f84094df5.png)

and best regards my homat @damahsyari: D

**Comment by mys** [comment]
Very thanks for design! I am not sure if these suits our needs tho :/
