### ISSUE TITLE
$LNG['sys_expe_attack_1_3_3'] missing message

### ISSUE THREAD

**Issue by mys** [steemnova/steemnova#12]
$LNG['sys_expe_attack_1_3_3'] expedition message is missing. It is negative encounter, alien fight.

![image](https://user-images.githubusercontent.com/17079510/35776367-806ff8e2-099b-11e8-93cb-b0c5181a3d57.png)

**Comment by Ravikin** [comment]
Probably fixed in  #7

**Comment by mys** [comment]
Polish translation updated by missing $LNG https://github.com/steemnova/steemnova/pull/7

**Comment by mys** [comment]
Get default English for missing messages in other languages https://github.com/steemnova/steemnova/pull/61

**Comment by mys** [comment]
Message still missing in other languages

**Comment by IntinteDAO** [comment]
Fixed
