### ISSUE TITLE
PHP error of Research view when abandon planet has started research technology

### ISSUE THREAD

**Issue by mys** [steemnova/steemnova#141]
>Message: Undefined offset: 286
File: /includes/pages/game/ShowResearchPage.class.php
Line: 314
URL: /game.php?page=research
PHP-Version: 7.0.28-0ubuntu0.16.04.1
PHP-API: apache2handler
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/pages/game/ShowResearchPage.class.php(314): errorHandler(8, 'Undefined offse...', 'FILEPATH ...', 314, Array)
#1 /includes/pages/game/ShowResearchPage.class.php(369): ShowResearchPage->getQueueData()
#2 /game.php(58): ShowResearchPage->show()
#3 {main}

286 is ID of abandon planet.

Solution: check if there are any started research technologies before abandoning planet.

**Comment by Qwatayean** [comment]
But on single queue or multiple queue? If is on multiple I believe the error will persist since it stores the planet id for queue. On my reproduction I got the error but must check if I did changes on the file since I was working on a fix.
