### ISSUE TITLE
Proposal For Copy writting 

### ISSUE THREAD

**Issue by Gallantmayor** [steemnova/steemnova#143]
Hello, i just checked your lovely project and i discovered you have some sections missing out like FAQ, about us, contact us and privacy policy. If you dont mind i will like to write that for you.

**Comment by mys** [comment]
Hey, there is already:
- [In game FAQ](https://github.com/steemnova/steemnova/blob/master/language/en/FAQ.php)
- [Abous us and contact us](https://github.com/steemnova/steemnova/blob/master/SteemNova%20About%20Us.md)
- [Privacy policy](https://github.com/steemnova/steemnova/blob/master/SteemNova%20Privacy%20Policy.md)
