### ISSUE TITLE
Error if deut consumption is 0 in fleet sending

### ISSUE THREAD

**Issue by Flugschwein** [steemnova/steemnova#172]
#### Expected behavior
When I want to send ships around, it is expected that I can do this as long as the deut consumption does not exceed the deut in the storage or in the cargo capacity.
#### Actual behavior
If the deut consumption for a fleet mission is zero, the cargo capacity gets shown as zero as well, even though it should be much higher. Also, if one presses continue, steemnova throws the following error:
```php
WARNING
--
Message: Division by zero
File: /includes/classes/class.FleetFunctions.php
Line: 187
URL: https://steemnova.intinte.org/game.php?page=fleetStep2
PHP-Version: 7.0.30-2
PHP-API: fpm-fcgi
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/classes/class.FleetFunctions.php(187): errorHandler(2, 'Division by zer...', 'FILEPATH ...', 187, Array)
#1 /includes/pages/game/ShowFleetStep2Page.class.php(88): FleetFunctions::GetFleetConsumption(Array, 5, 5, Array, 2)
#2 /game.php(58): ShowFleetStep2Page->show()
#3 {main}
```
As the error message states, this is caused by a division by zero. I think this is caused by the very high speed of spy drones, causing the duration of the of the flight to be rounded *down* to zero in the round expression in [that](https://github.com/steemnova/steemnova/blob/master/includes/classes/class.FleetFunctions.php#L187) line. Maybe this bug could be fixed by adding a `max()` statement in there. (so changing `round($MissionDuration, 0)` to `max(round($MissionDuration, 0), 1)`)
#### How to reproduce
<sup>(These steps assume you know how to play the game a bit.)</sup>
1. Get a running steemnova environment to test on. ([Here](https://steemit.com/utopian-io/@cryptoriddler/install-your-own-local-steemnova-server-in-a-few-minutes)'s a tutorial for setting up a local steemnova instance)
2. Get a moon besides one of your planets. (This can be done with the admin tools if you have admin permissions or by having some luck while playing the game)
3. Build some Spy Probes.
4. Try to send them to your moon.

* Browser/App version: Vivaldi | 1.15.1147.55 (Stable channel) (64-Bit)

**Comment by mys** [comment]
Looking quickly through the code, the $MissionDuration  minimum value is 5 (MIN_FLEET_TIME).
For game speed = 2 the formula
`(round($MissionDuration, 0) * $GameSpeed - 10)`
gives 0, as You got.

Have to test if we think correctly, but rounding it to `max(, 1)` or adding `+1` to the result could be the fix.
