### ISSUE TITLE
Display user status (S,N,VM,iI) in the Statistics and Alliance members view

### ISSUE THREAD

**Issue by mys** [steemnova/steemnova#177]

**Comment by Qwatayean** [comment]
From class.GalaxyRows, that should help! Since you want in more than one page, probably creating a function UserStatus($USERARRAY) on GeneralFunctions should do it

`				$Class		 		= array();

				if ($StatRow['banaday'] > TIMESTAMP && $StatRow['urlaubs_modus'] == 1)
				{
					$Class		 	= array('vacation', 'banned');
				}
				elseif ($StatRow['banaday'] > TIMESTAMP)
				{
					$Class		 	= array('banned');
				}
				elseif ($StatRow['urlaubs_modus'] == 1)
				{
					$Class		 	= array('vacation');
				}
				elseif ($StatRow['onlinetime'] < TIMESTAMP - INACTIVE_LONG)
				{
					$Class		 	= array('inactive', 'longinactive');
				}
				elseif ($StatRow['onlinetime'] < TIMESTAMP - INACTIVE)
				{
					$Class		 	= array('inactive');
				}`

**Comment by yamilrh** [comment]
Sería interesante que los aliados se vieran de un color: lime, y los enemigos se vieran de color:red,
algo que pueden agregar además es 
Remplazar en el archivo `shared.statistics.playerTable.tpl` 
`{$ShortStatus.$class}`
por
`<a class="tooltip" data-tooltip-content="{$LNG.gl_short_$class}">{$ShortStatus.$class}</a>`
en caso de error {$class}
Entonces agregar al idioma
`$LNG['strong']								= 'Jugador Fuerte';
$LNG['noob']								= 'Jugador Débil';
$LNG['vacation']							= 'Modo Vacaciones';
$LNG['banned']								= 'Baneado';
$LNG['inactive']							= 'Inactivo';`
esto hará que cuando le pongas el mouse arriba al status, te ponga el modo en el que está.

**Comment by Qwatayean** [comment]
This is not needed, in my opinion. I'd prefer to stick with ogame-like display.
