### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by spartaelcid** [steemnova/steemnova#181]
Hello,

maybe is only my problem and i not understand somethings, but i clone the project, and followed all the steps written in the readme, but I stop at the last step because it does not find the install.php file in that directory.

Did I do something wrong?

Thanks

**Comment by Qwatayean** [comment]
Hello.  What says in error.log file in "includes" folder?

A Sex, 2/11/2018, 09:14, spartaelcid <notifications@github.com> escreveu:
