### ISSUE TITLE
The BattleHall Page Displays Error Text

### ISSUE THREAD

**Issue by thewizardstudio** [steemnova/steemnova#186]
Clicking on 'Hall of Fame' while logged in takes the player to an error page.  This has been happening for several weeks.

https://steemnova.intinte.org/game.php?page=battleHall

NOTICE
--
Message: A non well formed numeric value encounteredFile: /cache/templates/en^49aa67543a3d88003c499564dd0cbe485faf04b6.page.battleHall.default.tpl.phpLine: 682URL: https://steemnova.intinte.org/game.php?page=battleHallPHP-Version: 7.2.9-1PHP-API: fpm-fcgi2Moons Version: 1.8.gitDebug Backtrace:#0 /cache/templates/en^49aa67543a3d88003c499564dd0cbe485faf04b6.page.battleHall.default.tpl.php(682): errorHandler(8, 'A non well form...', 'FILEPATH ...', 682, Array)#1 /includes/libs/Smarty/sysplugins/smarty_template_resource_base.php(128): content_5c8ca797e1b217_27800945(Object(Smarty_Internal_Template))#2 /includes/libs/Smarty/sysplugins/smarty_template_cached.php(136): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))#3 /includes/libs/Smarty/sysplugins/smarty_internal_template.php(179): Smarty_Template_Cached->render(Object(Smarty_Internal_Template), false)#4 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(199): Smarty_Internal_Template->render(false, 1)#5 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(114): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)#6 /includes/classes/class.template.php(137): Smarty_Internal_TemplateBase->display('extends:layout....')#7 /includes/pages/game/AbstractGamePage.class.php(270): template->display('extends:layout....')#8 /includes/pages/game/ShowBattleHallPage.class.php(69): AbstractGamePage->display('page.battleHall...')#9 /game.php(58): ShowBattleHallPage->show()#10 {main}

**Comment by Qwatayean** [comment]
It’s from PHP version. Removing the class on report foreach (it has no usage…) from template should fix it.

Enviado do Correio para Windows 10

De: The Wizard Studio
Enviado: 16 de março de 2019 17:40
Para: steemnova/steemnova
Cc: Subscribed
Assunto: [steemnova/steemnova] The BattleHall Page Displays Error Text (#186)

Clicking on 'Hall of Fame' while logged in takes the player to an error page. This has been happening for several weeks.
https://steemnova.intinte.org/game.php?page=battleHall
NOTICE
Message: A non well formed numeric value encounteredFile: /cache/templates/en^49aa67543a3d88003c499564dd0cbe485faf04b6.page.battleHall.default.tpl.phpLine: 682URL: https://steemnova.intinte.org/game.php?page=battleHallPHP-Version: 7.2.9-1PHP-API: fpm-fcgi2Moons Version: 1.8.gitDebug Backtrace:#0 /cache/templates/en^49aa67543a3d88003c499564dd0cbe485faf04b6.page.battleHall.default.tpl.php(682): errorHandler(8, 'A non well form...', 'FILEPATH ...', 682, Array)#1 /includes/libs/Smarty/sysplugins/smarty_template_resource_base.php(128): content_5c8ca797e1b217_27800945(Object(Smarty_Internal_Template))#2 /includes/libs/Smarty/sysplugins/smarty_template_cached.php(136): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))#3 /includes/libs/Smarty/sysplugins/smarty_internal_template.php(179): Smarty_Template_Cached->render(Object(Smarty_Internal_Template), false)#4 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(199): Smarty_Internal_Template->render(false, 1)#5 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(114): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)#6 /includes/classes/class.template.php(137): Smarty_Internal_TemplateBase->display('extends:layout....')#7 /includes/pages/game/AbstractGamePage.class.php(270): template->display('extends:layout....')#8 /includes/pages/game/ShowBattleHallPage.class.php(69): AbstractGamePage->display('page.battleHall...')#9 /game.php(58): ShowBattleHallPage->show()#10 {main}

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/187
