### ISSUE TITLE
Bash works on people, not planets.

### ISSUE THREAD

**Issue by IntinteDAO** [steemnova/steemnova#191]
By default Bash should work on planets, e.g. you can attack the same planet 6 times a day. In the 2moons engine it works on people, so one person can attack another e.g. 6 times a day.

**Comment by mys** [comment]
From what I can see Bash works vs planets. Here is SQL query https://github.com/steemnova/steemnova/blob/master/includes/classes/class.FleetFunctions.php#L507

I have send 8 simultaneous attacks versus one player (2 planets):
![image](https://user-images.githubusercontent.com/17079510/71482445-eb3e5d80-2802-11ea-980c-c735333e66ed.png)

**Comment by IntinteDAO** [comment]
I think there's also an error where the amount of Bash is not checked.

But is $PlanetOwner (line 489) checked somewhere? Because SQL is executed, but never used?

**Comment by mys** [comment]
> But is $PlanetOwner (line 489) checked somewhere? Because SQL is executed, but never used?

See line 494
