### ISSUE TITLE
BugFixed giving alliance ranks

### ISSUE THREAD

**Issue by yamilrh** [steemnova/steemnova#197]
He detectado un error en las alianza cuando tu juego tiene bastante jugadores al ellos crear muchos rangos de alianzas dando el siguiente error
`Query-Code:UPDATE uni1_users SET ally_rank_id = 542 WHERE id = 194 AND ally_id = 398;"
File: /srv/www/dominio/htdocs/includes/classes/Database.class.php | Line: 126
URL: dominio/game.php?page=all…=admin&action=rank&ajax=1 | Version: 1.9.git
Stack trace:
#0 /includes/classes/Database.class.php(177): Database-&gt;_query('UPDATE %%USERS%...', Array, 'update')
#1 /includes/pages/game/ShowAlliancePage.class.php(1433): Database-&gt;update('UPDATE %%USERS%...', Array)
#2 /includes/pages/game/ShowAlliancePage.class.php(735): ShowAlliancePage-&gt;adminRank()
#3 /game.php(57): ShowAlliancePage-&gt;admin()
#4 {main}`

es porque en la BD esta mal el campo ally_rank_id esta así `ally_rank_id` tinyint(3) unsigned NOT NULL DEFAULT '0', y cuando excede el id de 3 dígitos da error para resolverlo es cambiar el valor de uni1_users ally_rank_id a int(10)

Corregir install.sql línea 755 por `ally_rank_id` int(10) unsigned NOT NULL DEFAULT '0',

**Comment by mys** [comment]
I suppose the Author assumed there won't be more than 100 Alliances in the game 😂
