### ISSUE TITLE
Fusion  Reactor & Energy Tech dependency

### ISSUE THREAD

**Issue by Meatroach** [steemnova/steemnova#198]
In Ogame the Fusion Reactor Energy Output is calculated with the Energy-Technology in mind. As of now in steemnova the Fusion Reactor is not very efficient.

Formulars can be found here: https://ogame.fandom.com/wiki/Fusion_Reactor

I suggest to implement these Values to make the Fusion Reactor more viable

**Comment by Qwatayean** [comment]
the formula is already implemented.

https://github.com/steemnova/steemnova/blob/master/install/install.sql#L970

it seems to be missing that efficiency factor only.

Meatroach <notifications@github.com> escreveu no dia sexta, 17/01/2020 à(s)
11:30:
