### ISSUE TITLE
SQLSTATE[HY000]: General error: 1364 Field 'ally_rank_id' doesn't have a default value

### ISSUE THREAD

**Issue by cnwillz** [steemnova/steemnova#202]
After register, I got this error.

`Query-Code:INSERT INTO uni1_users SET username = xxxxx, email = xxxxxxxxxxx@gmail.com, email_2 = xxxxxxxxxxx@gmail.com2, authlevel = 0, universe = 1, lang = en, ip_at_reg = ***.***.***.**, onlinetime = 1579836205, register_time = 1579836205, password = $2a$09$dziy3lM9KcuTFLRn6mXVxYvoAAMDmGg6THh7zIrvK3RuIu7vIGU2u, dpath = nova, timezone = Europe/Berlin, uctime = 0, darkmatter = 0;
File: /includes/classes/Database.class.php
Line: 126
URL: https://steemnova.intinte.org/index.php?page=vertify&i=124&k=68c27505dcc6c68b21642c7c73a1ea6f
PHP-Version: 7.2.26-1+0~20191218.33+debian10~1.gbpb5a34b
PHP-API: fpm-fcgi
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/classes/Database.class.php(185): Database->_query('INSERT INTO uni...', Array, 'insert')
#1 /includes/classes/PlayerUtil.class.php(172): Database->insert('INSERT INTO %%U...', Array)
#2 /includes/pages/login/ShowVertifyPage.class.php(59): PlayerUtil::createPlayer('1', '****', '$2a$09$dziy3lM9...', '*******@gmai...', 'en')
#3 /includes/pages/login/ShowVertifyPage.class.php(127): ShowVertifyPage->_activeUser()
#4 /index.php(62): ShowVertifyPage->show()
#5 {main}`

**Comment by mys** [comment]
Please verify MySQL server settings if `STRICT_TRANS_TABLES` is disabled
https://stackoverflow.com/questions/15438840/mysql-error-1364-field-doesnt-have-a-default-values/52004654#52004654

**Comment by IntinteDAO** [comment]
Fixed in SteemNova. It looks like the default value was NULL instead of 0 during the update. Everything is correct in the game code (on Github).

**Comment by yamilrh** [comment]
esto es cosa del php al actualizar a partir de 7.2.24 no tomó los campos vació como null o 0,

**Comment by mys** [comment]
> php al actualizar a partir de 7.2.24 no tomó los campos vació como null o 0

Evilness of PHP
