### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Mickyc94** [steemnova/steemnova#221]
![Untitled](https://user-images.githubusercontent.com/979191/83807674-60179c80-a6ab-11ea-921a-967f88784f87.png)

After install i get to localhost/admin.php and its a blank white screen, install said I had all correct versions for setup and can go to localhost but as soon as I login it goes to game.php and again is just a blank white screen. I am using Xampp so not sure if thats the issue but its php 7.4.1 im using.

Screenshot is the only screen I am able to access.

**Comment by Qwatayean** [comment]
php 7.4 >= is not totally supported yet

**Comment by Mickyc94** [comment]
> 
> 
> php 7.4 >= is not totally supported yet

Ahh I see, when I use 7.3.18 though I get this error, what is the correct version to use currently?

Warning: require_once(HTML/BBCodeParser2.php): failed to open stream: No such file or directory in C:\xampp2\htdocs\game.php on line 21

Fatal error: require_once(): Failed opening required 'HTML/BBCodeParser2.php' (include_path='C:/xampp2/htdocs/includes/libs/BBCodeParser2/:C:/xampp2/htdocs/:C:\xampp2\php\PEAR') in C:\xampp2\htdocs\game.php on line 21

**Comment by Qwatayean** [comment]
If you replace (on game.php)

`require_once('HTML/BBCodeParser2.php');`
to 
`require_once('includes/libs/BBCodeParser2/HTML/BBCodeParser2.php');`

works?

**Comment by Mickyc94** [comment]
> 
> 
> If you replace (on game.php)
> 
> `require_once('HTML/BBCodeParser2.php');`
> to
> `require_once('includes/libs/BBCodeParser2/HTML/BBCodeParser2.php');`
> 
> works?

Yeah that works, any idea how many additional pages that is in? as admin.php was also one.
