### ISSUE TITLE
How can a new player register?

### ISSUE THREAD

**Issue by DaPike** [steemnova/steemnova#222]
Hi@all,

I installed the game yesterday and thought everything is up and running.
But today I wanted to register a new player with the start/login side.
There is NO REGISTER button, link or something like that.
Only LOGIN for existing users.

![steem1](https://user-images.githubusercontent.com/6161720/83943286-18078f80-a7fb-11ea-99c5-ca9aa9aed585.jpg)

Is this correct?
Registration is not closed in the admin panel!

Thanks for help.

**Comment by Mickyc94** [comment]
Yeah I would like to know this aswell.

**Comment by IntinteDAO** [comment]
Yep, need to be fixed

**Comment by DaPike** [comment]
That's right. Found it also.

And by th way, recaptcha is also not really fixed in the table.
![steem2](https://user-images.githubusercontent.com/6161720/84025424-d35f2e00-a98b-11ea-9e89-a231fd7e7c76.jpg)

**Comment by Mickyc94** [comment]
Not sure about reCaptcha as Im not using that and have it disabled and register works fine otherwise. Maybe close this ticket and open a new one regarding reCaptcha. I cant test it so wouldnt know how to fix it.
