### ISSUE TITLE
reCAPTCHA no correct position!

### ISSUE THREAD

**Issue by DaPike** [steemnova/steemnova#223]
Hi@all,

I've tried to edit the register.css under ../styles/resource/css/login.
But everything I tried ended with no reaction.
The reCaptcha image is still on the same position. So you can not accept the rules to continue.
How can I fix it?

![steem2](https://user-images.githubusercontent.com/6161720/84142008-5ea3f680-aa54-11ea-9674-82072dd09ec6.jpg)

Thx for help!

**Comment by IntinteDAO** [comment]
Hello

The simplest solution is to (I think good)
find file styles/templates/login/page.register.default.tpl

And find similar text, and replace
	{if $recaptchaEnable}

			<div class="g-recaptcha" data-sitekey="{$recaptchaPublicKey}"></div>

	{/if}

**Comment by DaPike** [comment]
Perfect!
It's working very good now!
Thx a lot!!
