### ISSUE TITLE
Dark Matter link piniondz

### ISSUE THREAD

**Issue by DaPike** [steemnova/steemnova#224]
Hi@all,

under the DARK MATTER I can see a link to https://my.adress.com/steemnova/google.com/wallet
In the game it is signed with **piniondz**??

First of all: 
How can I delete this link?

Second:
How can a player earn DARK MATTER in the game?
Is there a way to click a link or something every X hours/days an the player will get XXX Dark Matter?

I don't want money for this but the player have to earn the DM by himself.
It's not useful for me, to make giveaways or something like this every day.

![steem3](https://user-images.githubusercontent.com/6161720/84185481-59b06880-aa8f-11ea-9788-f254e190686e.jpg)

Thx a lot for help!

EDIT:
Under 

steemnova/styles/templates/game

I found in template 

main.topnav.tpl

the link in line 33. I edited it like this:

`<div class="res_current" id="current_{$resourceData.name}" data-real="{$resourceData.current}">{$resourceData.current|number} <!-- {if $resourceID == 921} <br><a href="google.com/wallet">piniondz</a>{/if} --></div>`

Link piniondz is now disabled!

**Comment by Qwatayean** [comment]
The only way to earn dark matter for free is through expeditions or dark
matter collector ship sent to owned moon (if the ship is active ingame)

A terça, 9/06/2020, 18:25, DaPike <notifications@github.com> escreveu:

**Comment by DaPike** [comment]
Ok. But I don't have a ship that is called dark matter collector.
How can I create this?

Sorry but I can't find any soltion.

**Comment by Qwatayean** [comment]
First of all run this on database:
`UPDATE uni1_users SET class = 200 WHERE id = 220`

2moons default ships are disabled by default upon game installation (with class = 201, which is a not declared class in-game = will not display in game). Replacing the dm ship class to 200, will make it appear in-game.

After you run query, please clear cache or delete cache/cache.vars.php file.

Here you have how mission works:
https://github.com/steemnova/steemnova/blob/master/includes/classes/missions/MissionCaseFoundDM.class.php

According to class.FleetFunctions file (mission requirement handler), you need to send to YOUR MOON a Dark Matter collector ship, alone on fleet. Here is how it is unlocked the mission:
https://github.com/steemnova/steemnova/blob/master/includes/classes/class.FleetFunctions.php#L483

I hope I have helped.

**Comment by IntinteDAO** [comment]
Yep, this button should be deleted.

It was created because SteemNova allows you to earn small amounts of cryptocurrency, and SteemNova's concept was to allow the exchange of Dark Matter for a token in the RSK network, which was to be used for exchanges between users.

Rather, this link will have to be hidden in fact.
