### ISSUE TITLE
Ships base speed doesn't upgrade when research new engine

### ISSUE THREAD

**Issue by mys** [steemnova/steemnova#24]
Based on this table:
http://ogame.wikia.com/wiki/Base_Speed

Small Cargo base speed should be 10000 at 5lv Impulse Drive giving 20000 value.
Right now it is base 5000 giving only 10000 after factor.

The ships description text is correct.

**Comment by MWFIAE** [comment]
I made a pr to address this issue, the problem is I don't have the ability to test it right now. 

Also we need more coding to correctly set recycler speed, I would have done it, but i don't know the shipid ^^" 
( I copied the other id's from the GetShipConsumption method)

**Comment by mys** [comment]
Here are the fleet IDs
https://github.com/steemnova/steemnova/blob/master/language/en/TECH.php#L21

TODO recycler hyperspace/impulse drive upgrades

**Comment by MWFIAE** [comment]
Thank you :)

I made a ugly quickfix so everything should be working for now. (One would need to update the speed2 value in the database for the recycler to 4000 though...)

But a more dynamic approach should be implemented in the future! (And we would need to alter the table to include another column for speed3...). But I don't want to change to much with this pr, so I would save that for another time.
