### ISSUE TITLE
Expedition pirates and aliens tech should scale

### ISSUE THREAD

**Issue by mys** [steemnova/steemnova#27]
Pirates should have -3 tech levels, Aliens +3 tech levels
http://owiki.de/Expedition

**Comment by mys** [comment]
Cap at 10000?
https://github.com/steemnova/steemnova/blob/master/includes/classes/missions/MissionCaseExpedition.class.php#L241

**Comment by Qwatayean** [comment]
Well, personally, would scale pirates difficulty with current user status, both in ships and both in tech. Just a suggestion.

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/142
