### ISSUE TITLE
Steemnova - error message on friend request

### ISSUE THREAD

**Issue by MWFIAE** [steemnova/steemnova#29]
#### Expected behavior
It should be possible to send friend requests to other players independent of the users language. A website should never display technical error messages to the users. (Even though it helped me find the bug in this case.)

#### Actual behavior
The backend returns an error saying that the language variable is not defined. Making it impossible to send a friend request to an user with another language.

#### How to reproduce
1. Open [Steemnova](https://steemnova.intinte.org)
2. login
3. go to the statistics page
4. find a user from another country
5. try to send a friend request to the user 

(I'm german, if somebody wants to test it out )

#### Recording Of The Bug
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518569080/zpf5towrosw5wiwzuura.png)

#### Suggested Fix
In [this line](https://github.com/steemnova/steemnova/blob/master/includes/pages/game/ShowBuddyListPage.class.php#L122) 

```$Friend_LNG = new Language($language);``` 

should be replaced with 

```$Friend_LNG = new Language($row['lang']);``` 

Also it should be considered to disable the debug error messages

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mwfiae/steemnova-error-message-on-friend-request">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mys** [comment]
Utopian created this issue topic automatically? You have fixed it here https://github.com/steemnova/steemnova/pull/23

**Comment by MWFIAE** [comment]
Yeah, Utopian creates this issues once they are getting approved...
