### ISSUE TITLE
Merchant of Fleets bug (Steemnova)

### ISSUE THREAD

**Issue by barbarosa05** [steemnova/steemnova#35]
#### Expected behavior
Merchant of Fleets (Scrap Merchant in Ogame) should give player option to sell **any** type of fleet unit including solar satelites for some % of basic price. 
#### Actual behavior
There is option to sell only light cargo and missile launcher for 70% of basic price. 

#### How to reproduce
Go to Merchant of Fleets page
Check choose menu
Only 2 types of ships, no matter if you have ships on planet, or not.
Here is Your bug!

* Browser:  Google Chrome (doesn't matter)
* Operating system: Windows 7 (also doesn't matter)

#### Recording Of The Bug
Here is Screenshoot of Merchant of Fleet page. 
https://res.cloudinary.com/hpiynhbhq/image/upload/v1518788582/jxb0dgx6n4aje0uxxr9p.png

Links: https://github.com/steemnova/steemnova 
http://steemnova.intinte.org/

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@barbarossastudio/merchant-of-fleets-bug-steemnova">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Qwatayean** [comment]
Thats not a bug. Simply run update `uni1_config set trade_allowed_ships = '202,203,204,205,206,207,208,209,210,211,212,213,214,217,219,220';`

It can be set the amount of ships you want to be sold on scrapper

**Comment by barbarosa05** [comment]
It is not about amount but type of ship

21 lut 2018 4:06 PM "Roberto" <notifications@github.com> napisał(a):

**Comment by Qwatayean** [comment]
But that's not the amount, it's which ships should be sold. Ship 202 - small cargo, 203 - big cargo...

**Comment by barbarosa05** [comment]
But in menu is only small cargo and rocket turrent

21 lut 2018 4:14 PM "Roberto" <notifications@github.com> napisał(a):

**Comment by Qwatayean** [comment]
Yes, and what I posted is the query how to solve it for the devs of steemnova, so isn't really a bug but something they can configure by themselves.

**Comment by barbarosa05** [comment]
Well ok, but from user side this is bug

21 lut 2018 4:26 PM "Roberto" <notifications@github.com> napisał(a):
