### ISSUE TITLE
Wrong display when sorting of alliance members

### ISSUE THREAD

**Issue by louis88-steemit** [steemnova/steemnova#36]
#### Expected behavior
In the alliance overview, I would like to sort all members according to the points you have achieved. So I choose to sort by the current score and expect a correct list.

#### Actual behavior
If I want to look at the members list in the alliance administration and want to sort all members of the alliance according to the points you have reached, there is a wrong list.

Normally, the number of points should be displayed in ascending or descending order.

#### How to reproduce
As an administrator or member of an alliance, simply go to the members list

https://steemnova.intinte.org/game.php?page=alliance&mode=memberlist

and sort the players according to their score.

No specific browser version or operating system required. 

#### Recording Of The Bug
![animation](https://i.imgur.com/vpkFywG.gif)

   <sub> Animation of sorting the Points of our Alliance</sub>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@louis88/wrong-display-when-sorting-of-alliance-members">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/34

**Comment by louis88-steemit** [comment]
thank you

**Comment by mys** [comment]
The sorting by Coordinates and Registration still doesn't work as intended. The javascript library doesn't parse whole string but by first character one-by-one. Eg.: some February dates are sorted before January.

**Comment by MWFIAE** [comment]
It seems like the sorting doesn't work as intended for every single column^^
I just fixed the status sorting [as suggested by rivalzzz](https://steemit.com/utopian-io/@rivalzzz/better-sorting-for-status-in-alliance-memberlist)^^

**Comment by mys** [comment]
Points <1000 don't get sorted properly

**Comment by MWFIAE** [comment]
Yeah there was a conflict while merging my changes. 
I had a PR for the points and one for the status. And the status one has overriden the point correction
