### ISSUE TITLE
Bug in general vision when you are receiving material from another person

### ISSUE THREAD

**Issue by JillFeint** [steemnova/steemnova#39]
When they send you materials from another planet of another person, this generates an error that does not allow you to see your general vision and sends you a warning message:

This is the message.

![bug](https://user-images.githubusercontent.com/34822690/36453683-ff34c298-1666-11e8-8dd8-c75a2c5fa20b.gif)

If you want to see the error in a more detailed way you can enter the following link
https://utopian.io/utopian-io/@jillfeint/bug-in-general-vision-when-you-are-receiving-material-from-another-person

**Comment by JillFeint** [comment]
Qwatayean commented a day ago • 

the issue comes from language/es/FLEET.php . the language row is missing an additional argument (a missing %s or %d on the text)
--

**Comment by Qwatayean** [comment]
I'd recommend retranslalte the rows related with overview fleet from language/es/FLEET.php (copy paste from english version, for example) or find for the correct word (where debug tracker does not mention which row is wrong) since Spanish it's the only one giving this issue

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/61
