### ISSUE TITLE
Better sorting for status in alliance-memberlist

### ISSUE THREAD

**Issue by RivalzZz88** [steemnova/steemnova#42]
https://i.gyazo.com/324aeb2868f93e6eae9dc3e5579d92dc.png
#### Expected behavior
While I went to the alliance members list in the alliance overview I used the online and offline sorting function and noticed the bug there.
![](https://i.imgur.com/2SvzvO1.png)
### Actual behavior
When clicking on the Online Sort button at the top of the table, the member list sorts itself according to the current behaviour of the member, whether online offline or with a time since the last time the player was actively logged in.
https://i.imgur.com/2SvzvO1.png
#### How to reproduce
1) Register on steemnova. intinte. org
2) Apply to an alliance and request the necessary rights to view the alliance members.
3) In the alliance overview area, click on the link for the alliance members.
4) When clicking the online button in the upper table, the order of the members changes according to Online/Offline/Timer status.
5) Usually online first, then the timer and then the Offline time.
https://i.imgur.com/2SvzvO1.png

Browser:  Google Chrome version 63.0.3239.132 (official build) (64-bit)
Operating system: Win10 64bit

##### Recording Of The Bug
![](https://media.giphy.com/media/1oGpqspiYvqiLKYxe9/giphy.gif)

Here you can see the current bug in the gif.

https://i.imgur.com/2SvzvO1.png
![](https://i.imgur.com/EChx0qJ.png)
Here the list is displayed correctly in the correct order with Online first.

https://i.imgur.com/2SvzvO1.png
![](https://i.imgur.com/FnasBu9.png)
Here the list is displayed correctly in the correct order with the offline status first.
https://i.imgur.com/2SvzvO1.png

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@rivalzzz/better-sorting-for-status-in-alliance-memberlist">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/38
