### ISSUE TITLE
USER ERROR Message: SQLSTATE[23000] - SQL Message Error when accepting an alliance member

### ISSUE THREAD

**Issue by louis88-steemit** [steemnova/steemnova#43]
#### Expected behavior
I was expecting a successful message indicating that a new alliance member of the alliance has been accepted.

#### Actual behavior
When I was just about to accept a new member for the alliance, I received an SQL error instead of a successful message. Every time I see this url 

- https://steemnova.intinte.org/game.php?page=alliance&mode=admin&action=sendAnswerToApply&id=152

the same message appears. The message contains information that may be important and should not be visible to everyone.

#### How to reproduce
I assume that this error is displayed if you want to accept a member who has already been accepted.
* Browser: Chrome Version 64.0.3282.140 (Offizieller Build) (64-Bit)

* Operating system: Mac OSX

#### Recording Of The Bug
![https://i.imgur.com/bSSt6Gz.png](https://i.imgur.com/bSSt6Gz.png)
[https://i.imgur.com/bSSt6Gz.png](https://i.imgur.com/bSSt6Gz.png)

   

        USER ERROR
    Message: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'message_owner' cannot be null
    
    Query-Code:INSERT INTO uni1_messages SET message_owner	= , message_sender	= 134, message_time	= 1519078537, message_type	= 2, message_from	= AllianzD-A-CH [GER], message_subject = Sie wurden aufgenommen bei D-A-CH, message_text	= Hallo!
    Die Allianz D-A-CH hat Ihre Bewerbung akzeptiert.
    Begründung: 
    , message_unread	= 1, message_universe = 1;
    File: /includes/classes/Database.class.php
    Line: 126
    URL: https://steemnova.intinte.org/game.php?page=alliance&mode=admin&action=sendAnswerToApply&id=152
    PHP-Version: 7.0.27-1
    PHP-API: fpm-fcgi
    2Moons Version: 1.8.git
    Debug Backtrace:
    #0 /includes/classes/Database.class.php(185): Database->_query('INSERT INTO uni...', Array, 'insert')
    #1 /includes/classes/PlayerUtil.class.php(644): Database->insert('INSERT INTO %%M...', Array)
    #2 /includes/pages/game/ShowAlliancePage.class.php(1179): PlayerUtil::sendMessage(NULL, '134', 'AllianzD-A-CH [...', 2, 'Sie wurden aufg...', 'Hallo!<br>Die A...', 1519078537)
    #3 /includes/pages/game/ShowAlliancePage.class.php(735): ShowAlliancePage->adminSendAnswerToApply()
    #4 /game.php(57): ShowAlliancePage->admin()
    #5 {main}

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@louis88/user-error-message-sqlstate-23000-sql-message-error-when-accepting-an-alliance-member">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mys** [comment]
>I assume that this error is displayed if you want to accept a member who has already been accepted.

This was the reason^

Fix https://github.com/steemnova/steemnova/commit/3f6170fcc63825b1c7549389005b57cd5853863d
