### ISSUE TITLE
Steemnova - Attack report is in the wrong language

### ISSUE THREAD

**Issue by MWFIAE** [steemnova/steemnova#44]
## Expected behavior
Every message a user receives should be in the language he understands. 

## Actual behavior
If beeing attacked by an user with a different language the attack report that is sent to the defending player is in the language of the attacking player.

## How to reproduce
1. Open [Steemnova](https://steemnova.intinte.org)
2. login
3. play long enough to fall out of the noob protection
4. <b>get attacked by an user with a different language. </b>
5. <b>after the attack go into your messages and search for the attack report. </b>

## Recording Of The Bug
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519302359/hu6yxh8vsm51q6mubtz7.png)
<sub>I'm not sure which language it is, but surely not german</sub>

 ![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519302622/gaojyecmsqx0etxbwvat.png)
<sub>That's how it should be displayed</sub>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mwfiae/steemnova-attack-report-is-in-the-wrong-language">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mys** [comment]
Probably fixed in https://github.com/steemnova/steemnova/pull/40
