### ISSUE TITLE
Wrong characters when accepting a new alliance member

### ISSUE THREAD

**Issue by louis88-steemit** [steemnova/steemnova#45]
#### Expected behavior
When accepting a new alliance member, I expected all correct information with all correct details.

#### Actual behavior
If I want to add a new alliance member to the alliance, the title shows a "%s" placeholder for the actual name of the user applying to the alliance.

Furthermore there is a ">" in front of the Main Planet.

Furthermore, there is an error in the table under "Last Activity" with the umlaut "ä" in the German language.

This is done in the following URL:
https://steemnova.intinte.org/game.php?page=alliance&mode=admin&action=detailApply&id=167

#### How to reproduce
If you have an alliance and accept an application. 
I use Steemnova in German Language

* Browser: All Browser
* Operating system: Online

#### Recording Of The Bug

![enter image description here](https://i.imgur.com/ETYKoiY.png)
[https://i.imgur.com/ETYKoiY.png](https://i.imgur.com/ETYKoiY.png)
    
Thanks
@louis88

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@louis88/wrong-characters-when-accepting-a-new-alliance-member">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Qwatayean** [comment]
Well the problem comes from languages/de/INGAME.php.

Open https://github.com/steemnova/steemnova/blob/master/styles/templates/game/page.alliance.admin.mangeApply.tpl for orientation

**Comment by mys** [comment]
Fixed https://github.com/steemnova/steemnova/pull/41
