### ISSUE TITLE
No correct display of the number of members of an alliance as leader of an alliance

### ISSUE THREAD

**Issue by louis88-steemit** [steemnova/steemnova#46]
#### Expected behavior
As an alliance leader, I want to see the correct number of current and potential alliance members. In my example we have 20 members - but the alliance has a limit of 30 players.

#### Actual behavior
As an Alliance Leader I have the possibility to enter the maximum number of members in the alliance. In my case, I have increased the maximum number of alliance members to 30. In the Alliance overview page, however, the default value of 20/20 members is displayed instead of the 20/30 members entered. 

#### How to reproduce
Create an alliance in Steemnova and set the maximum number of members in the alliance settings. after setting the maximum amount of members go back to the alliance-overview as an leader of the alliance.

* Browser: All Browser
* Operating system: Any operating System - Online.

#### Recording Of The Bug
![twentyoftwenty](https://i.gyazo.com/fa8aee83294b82bc3090acf886ed09ea.png)    
Alliance overview with Wrong Display 20/20 Alliance Members

![twentyoftwenty](https://i.gyazo.com/2719d17d3fd2bf4190c8a8cc64edd74e.png) 
Alliance Settings where are currently 30 Members allowed.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@louis88/no-correct-display-of-the-number-of-members-of-an-alliance-as-leader-of-an-alliance">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Qwatayean** [comment]
The problem can come from 2 sources.

Bad template var being loaded
Bad var call on ShowAlliancePage.class.php

I cant check what is now since im at mobile, but is one of those two

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/100
