### ISSUE TITLE
Fleet menu: Wrong Shield and Armor bonus display (steemnova)

### ISSUE THREAD

**Issue by barbarosa05** [steemnova/steemnova#48]
#### Expected behavior
The bonus is given by level of technology and officers bonus. For example I have 5 level of armour technology which gives me 50% and 5 level of admiral and 2 level of Engineer (screen 1) i should have 85% defence bonus. 
#### Actual behavior
I have 5 level of Armour technology and 5 level of admiral and 2 level of Engineer, but it displays me 105%, shield should be 95% but is 75%

for me it looks like, in shields it takes armour level + admiral level and in armour it takes shield level + engineer and admiral level 

#### How to reproduce
1. You should have armour technology, shield technology, Admiral and Engineer  on some level
2. Then calculate right values based on technology dectriptions and compare it with display bonuses in fleet menu
3. values will be different.

* Browser:  Chrome 
* Operating system: Windows 7

#### Recording Of The Bug

![Zrzut ekranu 2018-02-27 15.26.22.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519744936/v6twxtukph1chphor5bh.png)

![Zrzut ekranu 2018-02-27 15.26.14.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519744938/xs8bdox6rzaqazryntna.png)

![Zrzut ekranu 2018-02-27 15.26.01.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519744941/lpe9r9uj0giibzfotrvh.png)

Links: https://steemnova.intinte.org   and https://github.com/steemnova/steemnova

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@barbarossastudio/fleet-menu-wrong-shield-and-armor-bonus-display-steemnova">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Qwatayean** [comment]
This is not a bug, just a bad translation that has been there for ages. It should say additional 5% instead of 5% only. Officers have same behaviour of additional bonus just like Research

**Comment by barbarosa05** [comment]
This in not about translation shield is taken from armour technology and
vice versa

1 mar 2018 12:04 PM "Roberto" <notifications@github.com> napisał(a):

**Comment by mys** [comment]
The same applies in combat system file https://github.com/steemnova/steemnova/blob/master/includes/classes/missions/functions/calculateAttack.php
The 'shield' is armor and the 'def' is shield. However in calculateAttack.php the values are good, just mixed variables naming,
