### ISSUE TITLE
Error on Expedition - No Way to turn Back and Error: This page not exist

### ISSUE THREAD

**Issue by louis88-steemit** [steemnova/steemnova#52]
#### Expected behaviore
When I start an expedition in the browser game Steemnova but **forget** or be to fast to click on the point I want to start an expedition, I expect a correct error message and a back button so that I can enter my data again.

#### Actual behavior
Currently it is unfortunately the case that if you want to start an expedition, the only button available is not automatically selected. So it is unfortunately possible to start a mission without selecting the "Expedition" directly. After clicking on continue you get an error message that has nothing to do with an expedition. If you click on the next button "back" an error message will be displayed again without any indication of an error. See screenshots.

Unfortunately, you have to go back to your fleet and start the mission all over again.

#### How to reproduce
Start an expedition. When selecting the mission do not click the radio button for the mission. Continue with "continue". You will get an error message.
* Browser: All Browser - Browsergame
* Operating system: All Systems

### First Step
![first](https://i.imgur.com/eSQVNfk.png)

<sub> Select your Fleet for Expedition and check to Planet 16</sub>

### Second  Step
![second](https://i.imgur.com/ab1OWOn.png)

<sub>In the Next Step do **not** choose Radio Button Exedition</sub>

### Third Step
![third](https://i.imgur.com/oRHx5yq.png)

<sub>You will recieve an Error Message "No raw materials loaded!"</sub>

### Fourth Step

![fourth](https://i.imgur.com/Av5nMAD.png)

<sub>After hitting the Back Button you will see this message</sub>

The Last Step shows a Error - **This page does not exist**.

![animation](https://media.giphy.com/media/ksp8cUFmtDv0cmb8Au/giphy.gif)

#### What would be the solution in my opinion
The solution would be quite simple. If only one mission can be selected at all, the Radio button should be enabled by default.

Thanks
@louis88

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@louis88/error-on-expedition-no-way-to-turn-back-and-error-this-page-not-exist">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dotevo** [comment]
I fixed the error but still default "select"'s needed
