### ISSUE TITLE
Fleet menu: Wrong transport mission bug 

### ISSUE THREAD

**Issue by barbarosa05** [steemnova/steemnova#58]
#### Expected behavior
After selecting the wrong transport mission, the player should be moved to the fleet menu:
(https://steemnova.intinte.org/game.php?page=fleetTable)

#### Actual behavior
After selecting the wrong transport mission, the the player is moved to a page that does not exist:
https://steemnova.intinte.org/game.php?page=fleet2

#### How to reproduce
1) Go to fleet menu
2) Select planet and ships
3) Sent fleet on transport mission but **do not take any resources** 
4) Try to send fleet
5) Here is your bug
 
* Browser:  Chrome
* Operating system: Windows 7

#### Recording Of The Bug
![20180311_170133.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520784601/e8zs6s2zvxjvwsw3ftp5.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@barbarossastudio/fleet-menu-wrong-transport-mission-bug">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dotevo** [comment]
This fix is in the part of my PR
