### ISSUE TITLE
Error Occurs When Purchasing a Free Transaction from Marketplace

### ISSUE THREAD

**Issue by thewizardstudio** [steemnova/steemnova#60]
#### EXPECTED BEHAVIOR
Clicking 'Buy Now' on a free transaction in the Marketplace completes the order.

#### ACTUAL BEHAVIOR
Clicking 'Buy Now' on a free transaction in the Marketplace causes an error.

#### HOW TO REPRODUCE
1. Login to http://steemnova.intinte.org on Chrome 65.0.3325.109 using Android 8.1
2. Click on Marketplace in Left Menu
3. Locate a Transaction costing 0 Resources
4. Click 'Buy Now!'

#### TESTING ENVIRONMENT
- **OS**: Android 8.1 <br>
- **Browser**: Chrome 65.0.3325.109 <br>
- **App Version**: 1.8.0 <br>

#### RECORDING OF THE BUG
![FreeMarketError.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520954786/szufrrqavg7pmhrbazic.gif)

#### ERROR TEXT

WARNING
Message: Division by zero
File: /includes/classes/class.FleetFunctions.php
Line: 120
URL: https://steemnova.intinte.org/game.php?page=marketPlace&action=buy
PHP-Version: 7.0.28-1
PHP-API: fpm-fcgi
2Moons Version: 1.8.git
Debug Backtrace:
#0 /includes/classes/class.FleetFunctions.php(120): errorHandler(2, 'Division by zer...', 'FILEPATH ...', 120, Array)
#1 /includes/pages/game/ShowMarketPlacePage.class.php(110): FleetFunctions::GetMissionDuration(3500, 0, 9065, 2, Array)
#2 /includes/pages/game/ShowMarketPlacePage.class.php(211): ShowMarketPlacePage->doBuy()
#3 /game.php(57): ShowMarketPlacePage->show()
#4 {main}

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/error-occurs-when-purchasing-a-free-transaction-from-marketplace">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/59/commits/b59ee8a0f8f6696a13f5ce9263725edd67ecc0c7
