### ISSUE TITLE
Parallel action (building res. lab and research)

### ISSUE THREAD

**Issue by dotevo** [steemnova/steemnova#79]
#### Expected behavior
It should be not possible to build research lab and do research on all planets at the same time.

#### Actual behavior
It is possible to do those actions parallel.

#### How to reproduce
Init: You need 2 or more planets
1. Start building the lab on the planet X
2. Start research on planet Y

In different order problem does not exist.
* Browser: Firefox
* Operating system: Linux

#### Recording Of The Bug
Bug gif:
![Peek_2018-03-20_22-27.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521619841/clguizvflkrpk0nqlc7r.gif)

Different order of actions:
 ![Peek_2018-03-20_22-26.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521619836/g6qr9v9zbe0xyaicatsw.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@dotevo/parallel-action-building-res-lab-and-research">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/71
