### ISSUE TITLE
Steemnova - Marketplace bug, no confirmation message for trading

### ISSUE THREAD

**Issue by MWFIAE** [steemnova/steemnova#81]
### Expected behavior
There should be a confirmation message before trading, so users don't buy anything by accident.
And there shouldn't be any javascript errors in the console.

### Actual behavior
The confirmation message doesn't appear, because of a javascript error. 

This is caused by missing quotes around the message "Are you sure?".
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521812745/klhtrbenubbdyfnwjh0d.png)

This is how it should look like:
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521812930/sazw0tsacqf9zpbpo8dk.png)

### How to reproduce
The bug can be easily reproduced by visiting the marketplace in the [SteemNova-Game](https://steemnova.intinte.org/game.php?page=marketPlace)

* Browser: latest Chrome (shouldn't matter)
* Operating system: Windows10 (shouldn't matter)
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mwfiae/steemnova-marketplace-bug-no-confirmation-message-for-trading">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/76
