### ISSUE TITLE
[FEATURE] Ongoing research preview in Overwiev tab

### ISSUE THREAD

**Issue by Ravikin** [steemnova/steemnova#9]
## Idea
* Be possible to look at ongoing research from overview tab just like ongoing buildings below the planet image

![Ongoing research below planet image](https://user-images.githubusercontent.com/15932670/35682729-0197dc78-0762-11e8-993f-25f12f6293e5.png)

**Comment by Qwatayean** [comment]
This already exists but it's commented in smarty ( {* code *} )

https://github.com/steemnova/steemnova/blob/master/styles/templates/game/page.overview.default.tpl#L78

**Comment by mys** [comment]
@Qwatayean genius! It was already there..
https://github.com/steemnova/steemnova/commit/903a0726517cd7931fbf007d4a3951d6a2a6f37f

Todo: show research/ships build status of the other planets.
