### ISSUE TITLE
Wrong Information shown when a User applied to the Alliance

### ISSUE THREAD

**Issue by louis88-steemit** [steemnova/steemnova#92]
#### Expected behavior
If in the game Steemnova a new player of an alliance applies in his application information about himself and his score are displayed to make it easier for the administrator of the alliance to give a judgement about acceptance or refusal. Unfortunately, the information currently displayed is incorrect. The correct player information should be displayed.

#### Actual behavior
Currently, if a new player applies to an alliance and you look at the information about the player (see screenshots), completely wrong information is displayed here. Information is not displayed from the competing player, but information from the player who is in 27th place in the ranking. At least the display where his planet is and the username is correct. The battle statistics display is also correct. But this is not good information to decide if the user should join the alliance or not.

#### How to reproduce
Play the game Steemnova ([Github Link](https://github.com/steemnova/steemnova)) and form an alliance. Ask a friend to apply in your alliance and in the application you will see the wrong information about the user.

* Browser: All Browser  because Browser Game
* Operating system: All Systems because Browser Game

#### Recording Of The Bug
![Screen1](https://i.imgur.com/9OMA7LL.png)
    
 <sub> This screenshot shows the application in the alliance with the wrong information </sub>

----------

![screen2](https://i.imgur.com/wgjPCmz.png)

<sub>This screenshot shows that the new user has no points at all and has registered completely new.</sub>

----------

![screen3](https://i.imgur.com/3KoShYt.png)

<sub> This screenshot shows the information that is wrongly displayed to the user who applied. </sub>

Would be great if the bug could be fixed soon.

Thank you

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@louis88/wrong-information-shown-when-a-user-applied-to-the-alliance">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mys** [comment]
Fix https://github.com/steemnova/steemnova/pull/77
